name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repo
        uses: actions/checkout@master
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: harbor.blah.cloud
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: |
            mylesagray/tanzu-cnr-eventing-workshop:${{ secrets.GITHUB_RUN_NUMBER }}
            mylesagray/tanzu-cnr-eventing-workshop:latest
            ghcr.io/mylesagray/tanzu-cnr-eventing-workshop:${{ secrets.GITHUB_RUN_NUMBER }}
            ghcr.io/mylesagray/tanzu-cnr-eventing-workshop:latest
            harbor.blah.cloud/mylesagray/tanzu-cnr-eventing-workshop:${{ secrets.GITHUB_RUN_NUMBER }}
            harbor.blah.cloud/mylesagray/tanzu-cnr-eventing-workshop:latest
          file: ./Dockerfile
